"""add citation edges

Revision ID: 0a998508d17b
Revises: 5354a215b027
Create Date: 2026-09-23 18:34:26.187435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a998508d17b'
down_revision: Union[str, Sequence[str], None] = '5354a215b027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=512), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_ref', sa.String(length=512), nullable=False),
    sa.Column('treatment', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_edges_source_ref'), 'citation_edges', ['source_ref'], unique=False)
    op.create_index(op.f('ix_citation_edges_target_ref'), 'citation_edges', ['target_ref'], unique=False)
    op.create_index('ix_citation_source', 'citation_edges', ['source_kind', 'source_ref'], unique=False)
    op.create_index('ix_citation_target', 'citation_edges', ['target_kind', 'target_ref'], unique=False)
    # note: search_entries GIN expression index is intentionally preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citation_target', table_name='citation_edges')
    op.drop_index('ix_citation_source', table_name='citation_edges')
    op.drop_index(op.f('ix_citation_edges_target_ref'), table_name='citation_edges')
    op.drop_index(op.f('ix_citation_edges_source_ref'), table_name='citation_edges')
    op.drop_table('citation_edges')
    # ### end Alembic commands ###
