"""content-address ingestion_runs

Revision ID: 19c010d399ee
Revises: 2d06344c6414
Create Date: 2026-09-29 16:07:34.650135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c010d399ee'
down_revision: Union[str, Sequence[str], None] = '2d06344c6414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_runs', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_run_source_key'), 'ingestion_runs', type_='unique')
    op.create_unique_constraint('uq_run_source_key_hash', 'ingestion_runs', ['source_id', 'ingest_key', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_run_source_key_hash', 'ingestion_runs', type_='unique')
    op.create_unique_constraint(op.f('uq_run_source_key'), 'ingestion_runs', ['source_id', 'ingest_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('ingestion_runs', 'content_hash')
    # ### end Alembic commands ###
