"""add ingestion pipeline runs

Revision ID: 2d06344c6414
Revises: 7445073ce2fd
Create Date: 2026-09-29 16:06:37.017422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d06344c6414'
down_revision: Union[str, Sequence[str], None] = '7445073ce2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingest_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('normalizer_version', sa.String(length=64), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ingest_key', name='uq_run_source_key')
    )
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('run_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('artifact_key', sa.String(length=512), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('normalizer_version', sa.String(length=64), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_artifacts_run_id'), 'run_artifacts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_artifacts_run_id'), table_name='run_artifacts')
    op.drop_table('run_artifacts')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
