"""legal chunk embeddings

Revision ID: 3c328e6ba017
Revises: 19c010d399ee
Create Date: 2026-09-29 17:02:48.971256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c328e6ba017'
down_revision: Union[str, Sequence[str], None] = '19c010d399ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_chunks', sa.Column('embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_chunks', 'embedding')
    # ### end Alembic commands ###
