"""add search entries

Revision ID: 4a7c5fe46504
Revises: f5417128c2b0
Create Date: 2026-09-23 18:17:40.226432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7c5fe46504'
down_revision: Union[str, Sequence[str], None] = 'f5417128c2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('canonical_ref', sa.String(length=512), nullable=False),
    sa.Column('canonical_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('ref_law', sa.String(length=64), nullable=True),
    sa.Column('ref_article', sa.String(length=64), nullable=True),
    sa.Column('ecli', sa.String(length=128), nullable=True),
    sa.Column('case_number', sa.String(length=128), nullable=True),
    sa.Column('court', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'canonical_ref', name='uq_search_kind_ref')
    )
    op.create_index(op.f('ix_search_entries_canonical_id'), 'search_entries', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_search_entries_kind'), 'search_entries', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_entries_kind'), table_name='search_entries')
    op.drop_index(op.f('ix_search_entries_canonical_id'), table_name='search_entries')
    op.drop_table('search_entries')
    # ### end Alembic commands ###
