"""relevance feedback

Revision ID: 500a6c1656b7
Revises: 3c328e6ba017
Create Date: 2026-09-29 17:07:16.469634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500a6c1656b7'
down_revision: Union[str, Sequence[str], None] = '3c328e6ba017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relevance_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('canonical_ref', sa.String(length=512), nullable=False),
    sa.Column('judgement', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relevance_feedback_org_id'), 'relevance_feedback', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relevance_feedback_org_id'), table_name='relevance_feedback')
    op.drop_table('relevance_feedback')
    # ### end Alembic commands ###
