"""initial schema

Revision ID: 507295a30f2f
Revises: 
Create Date: 2026-09-23 17:45:14.369199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507295a30f2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=True)
    op.create_table('legal_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('remote_ai_policy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('raw_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_canonical_key'), 'source_documents', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('official_source', sa.Boolean(), nullable=False),
    sa.Column('primary_source', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('reuse_status', sa.String(length=32), nullable=False),
    sa.Column('licence', sa.String(length=255), nullable=True),
    sa.Column('licence_url', sa.String(length=1024), nullable=True),
    sa.Column('commercial_reuse_allowed', sa.Boolean(), nullable=False),
    sa.Column('automated_access_allowed', sa.Boolean(), nullable=False),
    sa.Column('bulk_download_allowed', sa.Boolean(), nullable=False),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('terms_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_checked_by', sa.String(length=255), nullable=True),
    sa.Column('terms_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('adapter_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('raw_object_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.String(length=128), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('legislation_node_id', sa.UUID(), nullable=True),
    sa.Column('judgment_paragraph_id', sa.UUID(), nullable=True),
    sa.Column('matter_document_id', sa.UUID(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_user')
    )
    op.create_table('matter_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'user_id', name='uq_matter_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matter_members')
    op.drop_table('memberships')
    op.drop_table('matters')
    op.drop_table('evidence')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_canonical_key'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_table('orgs')
    op.drop_table('legal_sources')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
