"""initial canonical schema

Revision ID: 5097d44a2bc1
Revises: 
Create Date: 2026-09-29 15:40:53.068759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5097d44a2bc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firm_precedents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_precedents_org_id'), 'firm_precedents', ['org_id'], unique=False)
    op.create_table('followed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('follow_key', sa.String(length=512), nullable=False),
    sa.Column('follow_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'follow_key', name='uq_followed')
    )
    op.create_index(op.f('ix_followed_items_org_id'), 'followed_items', ['org_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=True)
    op.create_table('jurisdictions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_terms', sa.JSON(), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('legal_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matter_authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('canonical_ref', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'matter_id', 'canonical_ref', name='uq_authority')
    )
    op.create_index(op.f('ix_matter_authorities_matter_id'), 'matter_authorities', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_authorities_org_id'), 'matter_authorities', ['org_id'], unique=False)
    op.create_table('matter_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_documents_matter_id'), 'matter_documents', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_documents_org_id'), 'matter_documents', ['org_id'], unique=False)
    op.create_table('matter_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_events_matter_id'), 'matter_events', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_events_org_id'), 'matter_events', ['org_id'], unique=False)
    op.create_table('matter_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_facts_matter_id'), 'matter_facts', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_facts_org_id'), 'matter_facts', ['org_id'], unique=False)
    op.create_table('matter_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_fact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_issues_matter_id'), 'matter_issues', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_issues_org_id'), 'matter_issues', ['org_id'], unique=False)
    op.create_table('model_run_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('remote_ai_policy', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('procedural_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('calculate_mode', sa.String(length=32), nullable=False),
    sa.Column('base_days', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('limit_type', sa.String(length=16), nullable=False),
    sa.Column('ambiguous', sa.Boolean(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('law_ref', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version_number', name='uq_rule_version')
    )
    op.create_index(op.f('ix_procedural_rules_rule_key'), 'procedural_rules', ['rule_key'], unique=False)
    op.create_table('search_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('canonical_ref', sa.String(length=512), nullable=False),
    sa.Column('canonical_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('ref_law', sa.String(length=64), nullable=True),
    sa.Column('ref_article', sa.String(length=64), nullable=True),
    sa.Column('ecli', sa.String(length=128), nullable=True),
    sa.Column('case_number', sa.String(length=128), nullable=True),
    sa.Column('court', sa.String(length=128), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'canonical_ref', name='uq_search_kind_ref')
    )
    op.create_index(op.f('ix_search_entries_canonical_id'), 'search_entries', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_search_entries_kind'), 'search_entries', ['kind'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('raw_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_canonical_key'), 'source_documents', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('official_source', sa.Boolean(), nullable=False),
    sa.Column('primary_source', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('reuse_status', sa.String(length=32), nullable=False),
    sa.Column('licence', sa.String(length=255), nullable=True),
    sa.Column('licence_url', sa.String(length=1024), nullable=True),
    sa.Column('commercial_reuse_allowed', sa.Boolean(), nullable=False),
    sa.Column('automated_access_allowed', sa.Boolean(), nullable=False),
    sa.Column('bulk_download_allowed', sa.Boolean(), nullable=False),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('terms_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_checked_by', sa.String(length=255), nullable=True),
    sa.Column('terms_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('adapter_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('raw_object_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('court_level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_el', sa.String(length=255), nullable=True),
    sa.Column('parent_court_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction', 'name', name='uq_court_jur_name')
    )
    op.create_index(op.f('ix_courts_jurisdiction'), 'courts', ['jurisdiction'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph', sa.String(length=128), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('legislation_node_id', sa.UUID(), nullable=True),
    sa.Column('judgment_paragraph_id', sa.UUID(), nullable=True),
    sa.Column('matter_document_id', sa.UUID(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_key', sa.String(length=255), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hierarchy_context', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('paragraph_number', sa.String(length=64), nullable=True),
    sa.Column('law_id', sa.UUID(), nullable=True),
    sa.Column('article_number', sa.String(length=64), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('source_locator', sa.JSON(), nullable=True),
    sa.Column('embedding_provider', sa.String(length=64), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('embedding_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_chunks_jurisdiction'), 'legal_chunks', ['jurisdiction'], unique=False)
    op.create_table('legal_sources_core',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_source', sa.Boolean(), nullable=False),
    sa.Column('primary_source', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_sources_core_jurisdiction'), 'legal_sources_core', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_legal_sources_core_source_key'), 'legal_sources_core', ['source_key'], unique=False)
    op.create_table('legislation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_canonical_id'), 'legislation', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_legislation_jurisdiction'), 'legislation', ['jurisdiction'], unique=False)
    op.create_table('matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_user')
    )
    op.create_table('judgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('court', sa.String(length=128), nullable=True),
    sa.Column('case_number', sa.String(length=255), nullable=True),
    sa.Column('ecli', sa.String(length=128), nullable=True),
    sa.Column('judgment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judges', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgments_canonical_id'), 'judgments', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_judgments_ecli'), 'judgments', ['ecli'], unique=False)
    op.create_index(op.f('ix_judgments_jurisdiction'), 'judgments', ['jurisdiction'], unique=False)
    op.create_table('legislation_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legislation_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legislation_id', 'node_type', 'number', name='uq_leg_node_identity')
    )
    op.create_index(op.f('ix_legislation_nodes_legislation_id'), 'legislation_nodes', ['legislation_id'], unique=False)
    op.create_table('legislation_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legislation_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('supersedes_version_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legislation_id', 'version_number', name='uq_leg_version')
    )
    op.create_index(op.f('ix_legislation_versions_legislation_id'), 'legislation_versions', ['legislation_id'], unique=False)
    op.create_table('matter_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matter_id', 'user_id', name='uq_matter_user')
    )
    op.create_table('case_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('source_case_id', sa.UUID(), nullable=True),
    sa.Column('source_case_key', sa.String(length=255), nullable=True),
    sa.Column('target_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('target_case_id', sa.UUID(), nullable=True),
    sa.Column('target_case_key', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('evidence_paragraph_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_case_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['target_case_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_treatment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_case_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('source_case_id', sa.UUID(), nullable=True),
    sa.Column('source_case_key', sa.String(length=255), nullable=True),
    sa.Column('target_case_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('target_case_id', sa.UUID(), nullable=True),
    sa.Column('treatment', sa.String(length=32), nullable=False),
    sa.Column('evidence_paragraph_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('extracted_by', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_case_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['target_case_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judgment_legislation_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judgment_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('judgment_id', sa.UUID(), nullable=True),
    sa.Column('judgment_key', sa.String(length=255), nullable=True),
    sa.Column('legislation_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('legislation_id', sa.UUID(), nullable=True),
    sa.Column('provision_node_id', sa.UUID(), nullable=True),
    sa.Column('provision_external_key', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('evidence_paragraph_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.ForeignKeyConstraint(['provision_node_id'], ['legislation_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('judgment_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judgment_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judgment_id', 'version_number', name='uq_judgment_version')
    )
    op.create_index(op.f('ix_judgment_versions_judgment_id'), 'judgment_versions', ['judgment_id'], unique=False)
    op.create_table('legislation_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('amending_legislation_id', sa.UUID(), nullable=True),
    sa.Column('affected_legislation_id', sa.UUID(), nullable=False),
    sa.Column('affected_node_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('previous_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('source_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affected_node_id'], ['legislation_nodes.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_amendments_jurisdiction'), 'legislation_amendments', ['jurisdiction'], unique=False)
    op.create_table('legislation_node_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('legislation_version_id', sa.UUID(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_locator', sa.JSON(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_versions.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['legislation_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'legislation_version_id', name='uq_node_version')
    )
    op.create_index(op.f('ix_legislation_node_versions_legislation_version_id'), 'legislation_node_versions', ['legislation_version_id'], unique=False)
    op.create_index(op.f('ix_legislation_node_versions_node_id'), 'legislation_node_versions', ['node_id'], unique=False)
    op.create_table('provision_cross_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('source_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('source_cross_jurisdiction_key', sa.String(length=255), nullable=True),
    sa.Column('target_node_id', sa.UUID(), nullable=True),
    sa.Column('target_jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('target_external_key', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('source_span_start', sa.Integer(), nullable=True),
    sa.Column('source_span_end', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction'], ['jurisdictions.code'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['legislation_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['legislation_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provision_cross_references_jurisdiction'), 'provision_cross_references', ['jurisdiction'], unique=False)
    op.create_table('judgment_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['judgment_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgment_sections_version_id'), 'judgment_sections', ['version_id'], unique=False)
    op.create_table('judgment_paragraphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('para_number', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['judgment_sections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['judgment_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgment_paragraphs_version_id'), 'judgment_paragraphs', ['version_id'], unique=False)
    # ### end Alembic commands ###

    # Bootstrap for either search (unaccent + GIN expression index)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
        op.execute(
            "CREATE OR REPLACE FUNCTION public.f_unaccent(text) RETURNS text AS "
            "$func$ SELECT public.unaccent('public.unaccent', $1) $func$ "
            "LANGUAGE sql IMMUTABLE PARALLEL SAFE")
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_search_entries_body_tsv ON search_entries "
            "USING gin (to_tsvector('simple', public.f_unaccent(body)))")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_judgment_paragraphs_version_id'), table_name='judgment_paragraphs')
    op.drop_table('judgment_paragraphs')
    op.drop_index(op.f('ix_judgment_sections_version_id'), table_name='judgment_sections')
    op.drop_table('judgment_sections')
    op.drop_index(op.f('ix_provision_cross_references_jurisdiction'), table_name='provision_cross_references')
    op.drop_table('provision_cross_references')
    op.drop_index(op.f('ix_legislation_node_versions_node_id'), table_name='legislation_node_versions')
    op.drop_index(op.f('ix_legislation_node_versions_legislation_version_id'), table_name='legislation_node_versions')
    op.drop_table('legislation_node_versions')
    op.drop_index(op.f('ix_legislation_amendments_jurisdiction'), table_name='legislation_amendments')
    op.drop_table('legislation_amendments')
    op.drop_index(op.f('ix_judgment_versions_judgment_id'), table_name='judgment_versions')
    op.drop_table('judgment_versions')
    op.drop_table('judgment_legislation_links')
    op.drop_table('case_treatment')
    op.drop_table('case_citations')
    op.drop_table('matter_members')
    op.drop_index(op.f('ix_legislation_versions_legislation_id'), table_name='legislation_versions')
    op.drop_table('legislation_versions')
    op.drop_index(op.f('ix_legislation_nodes_legislation_id'), table_name='legislation_nodes')
    op.drop_table('legislation_nodes')
    op.drop_index(op.f('ix_judgments_jurisdiction'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_ecli'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_canonical_id'), table_name='judgments')
    op.drop_table('judgments')
    op.drop_table('memberships')
    op.drop_table('matters')
    op.drop_index(op.f('ix_legislation_jurisdiction'), table_name='legislation')
    op.drop_index(op.f('ix_legislation_canonical_id'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_legal_sources_core_source_key'), table_name='legal_sources_core')
    op.drop_index(op.f('ix_legal_sources_core_jurisdiction'), table_name='legal_sources_core')
    op.drop_table('legal_sources_core')
    op.drop_index(op.f('ix_legal_chunks_jurisdiction'), table_name='legal_chunks')
    op.drop_table('legal_chunks')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_courts_jurisdiction'), table_name='courts')
    op.drop_table('courts')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_canonical_key'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_search_entries_kind'), table_name='search_entries')
    op.drop_index(op.f('ix_search_entries_canonical_id'), table_name='search_entries')
    op.drop_table('search_entries')
    op.drop_index(op.f('ix_procedural_rules_rule_key'), table_name='procedural_rules')
    op.drop_table('procedural_rules')
    op.drop_table('orgs')
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('model_run_logs')
    op.drop_index(op.f('ix_matter_issues_org_id'), table_name='matter_issues')
    op.drop_index(op.f('ix_matter_issues_matter_id'), table_name='matter_issues')
    op.drop_table('matter_issues')
    op.drop_index(op.f('ix_matter_facts_org_id'), table_name='matter_facts')
    op.drop_index(op.f('ix_matter_facts_matter_id'), table_name='matter_facts')
    op.drop_table('matter_facts')
    op.drop_index(op.f('ix_matter_events_org_id'), table_name='matter_events')
    op.drop_index(op.f('ix_matter_events_matter_id'), table_name='matter_events')
    op.drop_table('matter_events')
    op.drop_index(op.f('ix_matter_documents_org_id'), table_name='matter_documents')
    op.drop_index(op.f('ix_matter_documents_matter_id'), table_name='matter_documents')
    op.drop_table('matter_documents')
    op.drop_index(op.f('ix_matter_authorities_org_id'), table_name='matter_authorities')
    op.drop_index(op.f('ix_matter_authorities_matter_id'), table_name='matter_authorities')
    op.drop_table('matter_authorities')
    op.drop_table('legal_sources')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_followed_items_org_id'), table_name='followed_items')
    op.drop_table('followed_items')
    op.drop_index(op.f('ix_firm_precedents_org_id'), table_name='firm_precedents')
    op.drop_table('firm_precedents')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
