"""add matter workspace tables

Revision ID: 5354a215b027
Revises: a0767aa5ba0f
Create Date: 2026-09-23 18:27:53.269055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5354a215b027'
down_revision: Union[str, Sequence[str], None] = 'a0767aa5ba0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_documents_matter_id'), 'matter_documents', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_documents_org_id'), 'matter_documents', ['org_id'], unique=False)
    op.create_table('matter_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_events_matter_id'), 'matter_events', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_events_org_id'), 'matter_events', ['org_id'], unique=False)
    op.create_table('matter_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_facts_matter_id'), 'matter_facts', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_facts_org_id'), 'matter_facts', ['org_id'], unique=False)
    op.create_table('matter_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_fact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matter_issues_matter_id'), 'matter_issues', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_issues_org_id'), 'matter_issues', ['org_id'], unique=False)
    # NOTE: the search_entries GIN expression index is intentionally preserved.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matter_issues_org_id'), table_name='matter_issues')
    op.drop_index(op.f('ix_matter_issues_matter_id'), table_name='matter_issues')
    op.drop_table('matter_issues')
    op.drop_index(op.f('ix_matter_facts_org_id'), table_name='matter_facts')
    op.drop_index(op.f('ix_matter_facts_matter_id'), table_name='matter_facts')
    op.drop_table('matter_facts')
    op.drop_index(op.f('ix_matter_events_org_id'), table_name='matter_events')
    op.drop_index(op.f('ix_matter_events_matter_id'), table_name='matter_events')
    op.drop_table('matter_events')
    op.drop_index(op.f('ix_matter_documents_org_id'), table_name='matter_documents')
    op.drop_index(op.f('ix_matter_documents_matter_id'), table_name='matter_documents')
    op.drop_table('matter_documents')
    # ### end Alembic commands ###
