"""matter authority v2

Revision ID: 56dfebfaca51
Revises: 500a6c1656b7
Create Date: 2026-09-29 19:29:16.841494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dfebfaca51'
down_revision: Union[str, Sequence[str], None] = '500a6c1656b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matter_authorities', sa.Column('jurisdiction', sa.String(length=16), nullable=True))
    op.add_column('matter_authorities', sa.Column('authority_type', sa.String(length=32), nullable=True))
    op.add_column('matter_authorities', sa.Column('source_scope', sa.String(length=16), server_default=sa.text("'public'"), nullable=False))
    op.add_column('matter_authorities', sa.Column('authority_name', sa.String(length=512), nullable=True))
    op.add_column('matter_authorities', sa.Column('classification', sa.String(length=32), server_default=sa.text("'unclassified'"), nullable=False))
    op.add_column('matter_authorities', sa.Column('suggestion', sa.String(length=32), nullable=True))
    op.add_column('matter_authorities', sa.Column('suggestion_provenance', sa.String(length=32), nullable=True))
    op.add_column('matter_authorities', sa.Column('lawyer_note', sa.Text(), nullable=True))
    op.add_column('matter_authorities', sa.Column('saved_by', sa.UUID(), nullable=True))
    op.add_column('matter_authorities', sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matter_authorities', sa.Column('matter_issue', sa.String(length=512), nullable=True))
    op.add_column('matter_authorities', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('matter_authorities', sa.Column('temporal_applicability', sa.Text(), nullable=True))
    op.drop_column('matter_authorities', 'state')
    op.drop_column('matter_authorities', 'note')
    op.drop_column('matter_authorities', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matter_authorities', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('matter_authorities', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matter_authorities', sa.Column('state', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('matter_authorities', 'temporal_applicability')
    op.drop_column('matter_authorities', 'evidence')
    op.drop_column('matter_authorities', 'matter_issue')
    op.drop_column('matter_authorities', 'saved_at')
    op.drop_column('matter_authorities', 'saved_by')
    op.drop_column('matter_authorities', 'lawyer_note')
    op.drop_column('matter_authorities', 'suggestion_provenance')
    op.drop_column('matter_authorities', 'suggestion')
    op.drop_column('matter_authorities', 'classification')
    op.drop_column('matter_authorities', 'authority_name')
    op.drop_column('matter_authorities', 'source_scope')
    op.drop_column('matter_authorities', 'authority_type')
    op.drop_column('matter_authorities', 'jurisdiction')
    # ### end Alembic commands ###
