"""add case_treatment target_key

Revision ID: 7445073ce2fd
Revises: 5097d44a2bc1
Create Date: 2026-09-29 15:55:02.166874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7445073ce2fd'
down_revision: Union[str, Sequence[str], None] = '5097d44a2bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_treatment', sa.Column('target_case_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_treatment', 'target_case_key')
    # ### end Alembic commands ###
