"""add org plan

Revision ID: 8e3aad70737a
Revises: 0493f8d84891
Create Date: 2026-09-23 18:53:52.102834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3aad70737a'
down_revision: Union[str, Sequence[str], None] = '0493f8d84891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgs', sa.Column('plan', sa.String(length=32), server_default=sa.text("'starter'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgs', 'plan')
    # ### end Alembic commands ###
