"""add matter authorities + notifications

Revision ID: b23cab155aed
Revises: 8e3aad70737a
Create Date: 2026-09-23 18:57:26.346454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23cab155aed'
down_revision: Union[str, Sequence[str], None] = '8e3aad70737a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('follow_key', sa.String(length=512), nullable=False),
    sa.Column('follow_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'follow_key', name='uq_followed')
    )
    op.create_index(op.f('ix_followed_items_org_id'), 'followed_items', ['org_id'], unique=False)
    op.create_table('matter_authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('canonical_ref', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'matter_id', 'canonical_ref', name='uq_authority')
    )
    op.create_index(op.f('ix_matter_authorities_matter_id'), 'matter_authorities', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matter_authorities_org_id'), 'matter_authorities', ['org_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_org_id'), 'notifications', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_org_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_matter_authorities_org_id'), table_name='matter_authorities')
    op.drop_index(op.f('ix_matter_authorities_matter_id'), table_name='matter_authorities')
    op.drop_table('matter_authorities')
    op.drop_index(op.f('ix_followed_items_org_id'), table_name='followed_items')
    op.drop_table('followed_items')
    # ### end Alembic commands ###
