"""add procedural rules

Revision ID: bca956e3c4d0
Revises: 0a998508d17b
Create Date: 2026-09-23 18:38:37.143512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca956e3c4d0'
down_revision: Union[str, Sequence[str], None] = '0a998508d17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedural_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('calculate_mode', sa.String(length=32), nullable=False),
    sa.Column('base_days', sa.Integer(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('limit_type', sa.String(length=16), nullable=False),
    sa.Column('ambiguous', sa.Boolean(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('law_ref', sa.String(length=255), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version_number', name='uq_rule_version')
    )
    op.create_index(op.f('ix_procedural_rules_rule_key'), 'procedural_rules', ['rule_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedural_rules_rule_key'), table_name='procedural_rules')
    op.drop_table('procedural_rules')
    # ### end Alembic commands ###
