"""add corpus tables

Revision ID: f5417128c2b0
Revises: 44a43fb57fb4
Create Date: 2026-09-23 18:12:08.766884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5417128c2b0'
down_revision: Union[str, Sequence[str], None] = '44a43fb57fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('court', sa.String(length=128), nullable=True),
    sa.Column('case_number', sa.String(length=255), nullable=True),
    sa.Column('ecli', sa.String(length=128), nullable=True),
    sa.Column('judgment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgments_canonical_id'), 'judgments', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_judgments_ecli'), 'judgments', ['ecli'], unique=False)
    op.create_table('legislation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_canonical_id'), 'legislation', ['canonical_id'], unique=False)
    op.create_table('judgment_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judgment_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('judgment_id', 'version_number', name='uq_judgment_version')
    )
    op.create_index(op.f('ix_judgment_versions_judgment_id'), 'judgment_versions', ['judgment_id'], unique=False)
    op.create_table('legislation_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legislation_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('supersedes_version_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legislation_id', 'version_number', name='uq_leg_version')
    )
    op.create_index(op.f('ix_legislation_versions_legislation_id'), 'legislation_versions', ['legislation_id'], unique=False)
    op.create_table('judgment_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('para_number', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('segment_type', sa.String(length=32), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['judgment_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgment_nodes_version_id'), 'judgment_nodes', ['version_id'], unique=False)
    op.create_table('legislation_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_locator', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['legislation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_nodes_version_id'), 'legislation_nodes', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legislation_nodes_version_id'), table_name='legislation_nodes')
    op.drop_table('legislation_nodes')
    op.drop_index(op.f('ix_judgment_nodes_version_id'), table_name='judgment_nodes')
    op.drop_table('judgment_nodes')
    op.drop_index(op.f('ix_legislation_versions_legislation_id'), table_name='legislation_versions')
    op.drop_table('legislation_versions')
    op.drop_index(op.f('ix_judgment_versions_judgment_id'), table_name='judgment_versions')
    op.drop_table('judgment_versions')
    op.drop_index(op.f('ix_legislation_canonical_id'), table_name='legislation')
    op.drop_table('legislation')
    op.drop_index(op.f('ix_judgments_ecli'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_canonical_id'), table_name='judgments')
    op.drop_table('judgments')
    # ### end Alembic commands ###
